The peeweelinux-0.53.3 release.

diff --git a/pwlconfig b/pwlconfig
--- a/pwlconfig
+++ b/pwlconfig
@@ -7,9 +7,6 @@
 #    embedded targets. Use from command line or interactively.
 #
 # Options:
-#  -B, --boot         run lilo on project device for standalone booting
-#  -D, --dual-boot    run lilo on this drive to boot to project device
-#  -E, --erase        erase and format project device
 #  -e, --extract [source_dir]
 #                     extract files to source dir from project configuration
 #  -l, --load [source_dir [ device_mount_point ]]
@@ -63,29 +60,9 @@
 #      .xxx.list    - configuration in progress file
 #
 # History
-#    -v0.90 - Added Dual boot capability, fixed erase, use pwl usage, use
-#             project defaults where applicatable
-#    -v0.86 - maintain hidden .extract.log and .lilo.res files for debugging
-#             include device mount point (from project defaults) on Erase
-#    -v0.85 - fixed command line extraction process
-#    -v0.84 - more extraction of code
-#    -v0.82 - move Update to main menu, cleanup cleanups, proper lilo options
-#           - re-added feature to check custom source files by date
-#    -v0.8  - massive changes using multiple smaller scripts
-#    -v0.7a - speed ups and updating fixed, rm option for debug
-#    -v0.7b - use mkBootDevice script
-#    -v0.7c - split out defaults, custom and project functions into
-#             little scripts
-#    -v0.7d - added smart save, fix Update cmd for tar files
+# =======
 #
-#    v0.7 - bug fixes, added Update project function, split with pwl_custom
-#    v0.6 - bug fix to support 'nearly' matching filenames, added debug utilities
-#           re-worked command line parameters and added usage statement
-#    v0.5 - package selection from subdirectories; cleanup function names
-#    v0.4 - more major bug fixes, added file sizes to help figure system size
-#    v0.3 - major bug fixes, require root login to extract devices and DOC erase
-#    v0.2 - Added multiple configurations, custom files handling
-#    v0.1 - released not tested
+# see scripts/CHANGES.pwlconfig
 #
 #=============================================================================
 #
@@ -101,8 +78,6 @@ export usrMode="I"
 # include utility functions
 #
 . ./scripts/pwl_functions
-#
-PWL_VER=${PWL_REL_VER}".1"
 #
 #=============================================================================
 #=============================================================================
@@ -151,20 +126,32 @@ function build_main()
 {
    $decho "start build_main"
    if [ "$deviceName" = "" ] ; then
-      echo Internal error - set device
-      exit 0
+       #
+       # defective configuration prompt to fix
+       #
+       show_confirm "Internal error - set device" \
+           "No device has been set for this project. Probably because of a corrupted or non existant configuration file. Reset the configuration for $CFG_BASE?" "9"
+       if [ $? = "1" ] || [ $? = "255" ]; then
+           $decho "Nothing was done. User cancelled..."
+           exit 0
+       fi
+       $PRJ_DEFAULTS --reset FLASH
+       if [ "$?" = "1" ] ; then
+           cleanup 1
+       fi
+       default_define   # now load default variables
+       $decho "Reset configuration..."
    fi
 
    echo -n "'PkgConfig' 'Configure Project File System -->'             \
-            'Update'    'Update \"$CFG_BASE\" from File System --> '    \
+            'Update'    'Create or Update \"$CFG_BASE\" from File System --> ' \
             'Extract'   'Extract File System for Project'               \
             'skip'      '----'                                          \
-            'Erase'     'Erase $deviceName at $deviceLoc$devicePartition' \
-            'Load'      'Load File System onto $deviceName'             \
-            'Dual'      'Allow this system to dual-boot $deviceName'    \
-            'Lilo'      'Install LInux LOader (LILO) to $deviceName'    \
+            'Target'    'Configure Target Hardware -->'        \
+            'Load'      'Load File System onto Target $deviceName'      \
             'skip'      '----'                                          \
             'PrjManage' 'Manage Projects -->'                           \
+            'PkgManage' 'Manage Package Files -->'                      \
             'Save'      'Save Project'                                 "> $1
    #
    $decho "end build_main"
@@ -232,7 +219,7 @@ function extract_packages()
        tar_file=`basename $nfile_lst .list`".tar"
        #
        if [ ! -f "$pkgDir"/"$tar_file" ] ; then
-          echo $CFG_FILE Error: $pkgDir\$tar_file not found \(line "$ln"\)
+          echo "$CFG_FILE Error: $pkgDir/$tar_file not found (line $ln)"
 
        elif [ ! -f "$PWL_PRJ"/"$lst_file" ] ; then  # internal error ??
              echo Configuration list file $PWL_PRJ/$lst_file not found
@@ -304,18 +291,11 @@ function extract_project()
       mntName="$1"
 
    else
-      get_string "Build File System for project $CFG_BASE" \
+      get_string "Extract File System for project: $CFG_BASE" \
                  "Enter path and name of mount point:" \
                  "mntName" "$PWL_PRJ"/"$prjMnt"
       if [ $? != "0" -o "$mntName" = "" ] ; then
          return
-      fi
-   fi
-   #
-   if [ -d "$mntName" ] ; then
-      show_confirm "Mount Point Exists" "Remove File System created at: $mntName ?"
-      if [ $? != "0" ] ; then
-         return             # let user specify another mount point
       fi
    fi
    #
@@ -342,146 +322,6 @@ function extract_project()
    $decho "end extract_project"
 }
 
-#=============================================================================
-#
-# device_erase - erase device mounted (or re-mount) the device
-#
-function device_erase()
-{
-   $decho "start device_erase"
-   #
-   # get user defined mount point ??
-   #
-   get_string "Erase Device Contents" \
-              "Enter path and name of device mount point:"\
-              "destMntName" "$deviceMnt"
-   if [ $? != "0" ] ; then
-      return
-   fi
-   if [ ! -d "$destMntName" ] ; then
-      show_message "Mount point not found" \
-         "Mount point: $destMntName was not found"
-      return
-   fi
-   #
-   # confirm erase
-   #
-   show_confirm "Confirm Erase Device" \
-     "Are you sure you want to erase $deviceType device at $deviceLoc$devicePartition ?"
-   if [ $? = "0" ] ; then
-      #
-      # Erase it - note: if device is not mountable as is, we have to
-      #            erase it first before we mount it (-e then -m).
-      #
-      $DEV_MGR $deviceType --device $deviceLoc --dev-id $devicePartition --mount $destMntName -e -m |tee .erase.log
-      #
-      # tell them what happened
-      #
-      show_results .erase.log "Erase Device Results"
-      #
-      $RM .erase.log
-   fi
-   #
-   $decho "end device_erase"
-}
-
-#
-# device_dual_boot()
-#     Copies existing /etc/lilo.conf file and appends section to install
-#     the project device as a bootable option at power up.
-#
-function device_dual_boot()
-{
-   $decho "start device_dual_boot"
-   #
-   # get system boot device
-   #
-   sysBootDevice=`mount | head -1`
-   sysBootDevice=${sysBootDevice%%[0-9]*}
-   #
-   show_confirm "Update LILO on this machine" \
-"Boot device for this machine is: $sysBootDevice.  You are 
-about to Modify the Master Boot Record for this device. 
-Make sure you have a boot disk available!" 10
-   if [ $? != "0" ] ; then
-      return
-   fi
-   if [ "$destMntName" = "" ] ; then
-      destMntName="$deviceMnt"
-   fi
-   #
-   get_string "Allow LILO to access Device" \
-              "Enter path and name of device mount point:"\
-              "destMntName" $destMntName
-   if [ $? != "0" ] ; then
-      return
-   fi
-   if [ ! -d "$destMntName" ] ; then
-      show_message "Mount point not found" \
-         "Mount point: $destMntName was not found"
-      return
-   fi
-   #
-   # Lilo it - note root device is the same as the device location when
-   #           we dual boot - ignore bootDevice
-   #
-   $DEV_MGR  $deviceType --mbr-device $sysBootDevice --mount $destMntName \
-             --label $bootLabel --kernel $bootKernel --dev-id $devicePartition \
-             --device $deviceLoc --root-dev ${deviceLoc}${devicePartition} \
-             -m --dual-boot 2>&1 |tee .dlilo.log
-   #
-   show_results .dlilo.log "LILO on $deviceName"
-   #
-   $RM .dlilo.log
-   $decho "end device_dual_boot"
-}
-
-#
-# device_lilo()
-#        Builds a lilo.conf.DEVICE file to install the Linux Loader onto
-#        the device and all it to boot as a master boot device.
-#
-function device_lilo()
-{
-   $decho "start device_lilo"
-   #
-   # get user defined mount point
-   #
-   if [ "$destMntName" = "" ] ; then
-     destMntName="$deviceMnt"
-   fi
-   # 
-   get_string "Install LILO on Device" \
-              "Enter path and name of device mount point:"\
-              "destMntName" $destMntName
-   if [ $? != "0" ] ; then
-      return
-   fi
-   if [ ! -d "$destMntName" ] ; then
-      show_message "Mount point not found" \
-         "Mount point: $destMntName was not found"
-      return
-   fi
-   #
-   # Tell user about our defaults
-   #
-   show_message "Note on Lilo Configuration" \
-"Configuration parameters for LILO operation are stored in \
- \"lilo.conf.$deviceType\". Please verify these before attempting to boot this device!"
-   #
-   # Lilo it
-   #
-   $DEV_MGR  $deviceType --mount $destMntName \
-             --label $bootLabel --kernel $bootKernel \
-             --dev-id $devicePartition --mbr-device $bootDevice \
-             --device $deviceLoc --root-dev $bootDevice  -mb 2>&1 |tee .lilo.log
-   #
-   show_results .lilo.log "LILO on $deviceName"
-   #
-   $RM .lilo.log
-   $decho "end device_lilo"
-}
-
 #
 # device_load_fs( [ sourceMnt, deviceMntName ])
 #    Load file system created for this project onto the current device
@@ -491,59 +331,69 @@ function device_load_fs ()
 {
    $decho "start device_load_fs"
    #
-   # Get location of existing file system (show default)
+   # make sure we have a current default parameters
    #
-   if [ "$1" != "" ] ; then
-      srcMntName="$1"
-   else
-      get_string "Load File System: Source" \
-                 "Enter path and name of file system :" \
-                 "srcMntName" "$PWL_PRJ"/"$prjMnt"
-      if [ $? != "0" ] ; then
-         return
-      fi
+   # 1. case config file pre 0.53
+   #
+   if [ -z "$pwl_version" ]; then
+       $decho "incompatible defaults file..."
+       # show dialog box
+       show_confirm "Configuration File Incompatibility" \
+           "The configuration file is pre 0.53 and incompatible with PeeWeeLinux $PWL_VER. Reset the configuration for $CFG_BASE?" "9"
+       if [ $? = "1" ] || [ $? = "255" ]; then
+           $decho "Nothing was done. User cancelled..."
+       else
+           $PRJ_DEFAULTS --reset FLASH
+           if [ "$?" = "1" ] ; then
+               cleanup 1
+           fi
+           default_define   # now load default variables
+           show_message "Configuration Reset" \
+               "The configuration for $CFG_BASE has been reset. Please check settings"
+           $decho "Reset configuration..."
+       fi
+       return 1
    fi
-   if [ -z "$srcMntName" ] || [ ! -d "$srcMntName" ] ; then
-      show_message "Existing File System Not Found" \
-             "Could Not find $srcMntName. Make sure you have selected 'Extract File System for Project' first"
+   #
+   # ask for confirmation before building system
+   #
+   show_confirm "Load File System onto Target $deviceName" \
+          "You are about to install the extracted filesystem onto $deviceName. All existing content on $deviceName will be destroyed. Are you sure you wish to proceed?" "9"
+   if [ $? = "1" ] || [ $? = "255" ]; then
+      $decho "Nothing was done. User cancelled..."
       return
    fi
    #
-   # get user defined mount point
+   # execute commands to load the file system to the device
    #
-   if [ "$1" != "" -a "$2" != "" ] ; then
-      $decho "using destination parameter $2"
-      destMntName="$2"
+   . ./$PWL_TARGET >.load.log 
+   #
+   # show dialog with success or fail
+   #
+   if [ "$rd_fail" = "fail" ]; then
+       #
+       # load failed
+       #
+       show_confirm "Load File System onto Target $deviceName failed" \
+           "The target build script failed to load the filesystem onto the configured target. Do you wish to view the results?"
    else
-      if [ "$destMntName" = "" ] ; then
-         destMntName="$deviceMnt"
-      fi
-      get_string "Load File System: Destination" \
-                 "Enter path and name of device mount point:"\
-                 "destMntName" $destMntName
-      if [ $? != "0" ] ; then
-         return
-      fi
+       #
+       # load success
+       #
+       show_confirm "Load File System onto Target $deviceName succeeded" \
+           "The target build script succeeded in loading the configured target device. Do you wish to view the results?"
    fi
    #
-   if [ -z "$destMntName" ] ; then
-      return
+   # show results if selected
+   #
+   if [ $? = "1" ] || [ $? = "255" ]; then
+       #
+       $decho "Skip results..." 
+   else
+       #
+       show_results .load.log "Load $deviceName Results"
+       $decho "Show results..." 
    fi
-   #
-   # execute command to load the file system
-   #
-   $DEV_MGR  $deviceType --source $srcMntName --mount $destMntName \
-             --label $bootLabel --kernel $bootKernel --dev-id $devicePartition \
-             --device $deviceLoc --root-dev $bootDevice  -mc |tee .load.log
-   #
-   # Note: tee in above command kills status
-   #
-   echo "" >> .load.log
-   echo " Total Size of new file system: `du $destMntName -bsh` " >> .load.log
-   #
-   # view results
-   #
-   show_results .load.log "Load File System - Results"
    #
    $RM  .load.log
    $decho "end device_fs_load"
@@ -559,10 +409,10 @@ function menu_main()
    $decho "start menu_main"
    #
    mainDone=0
-   build_main .main.lst
    #
    while [ "$mainDone" = "0" ]; do
 
+      build_main .main.lst                # rebuild everytime - its cheap
       show_main .main.lst 2> .result
 
       retVal=$?
@@ -588,20 +438,18 @@ function menu_main()
                                      # files at mount point
                      $PWL_UPDATE
              ;;
-             "Erase")
-                     device_erase
+             "Target")
+                     $PRJ_DEFAULTS
+                     default_define   # reload if any defaults changed
              ;;
              "Load")
                      device_load_fs
              ;;
-             "Lilo")
-                     device_lilo
-             ;;
-             "Dual")
-                     device_dual_boot
-             ;;
              "Save")
                      confirm_save
+             ;;
+             "PkgManage")
+                   $PWL_PKGMGR
              ;;
              "PrjManage")
                      confirm_save
@@ -611,7 +459,6 @@ function menu_main()
                      else                   # reset defaults
                         pwl_init_project
                         default_define
-                        build_main .main.lst
                      fi
              ;;
         esac
@@ -645,6 +492,7 @@ function cleanup()
 function main_init()
 {
    $decho "start main_init"
+   echo -n "."
    #
    export backtitle="Pee Wee Linux System Configuration - Version $PWL_VER"
    progInfo=$backtitle
@@ -656,6 +504,7 @@ function main_init()
       cleanup  #not root user
    fi
    #
+   echo -n "."
    export CFG_BASE=none
    $PWL_PROJECTS --init
    status=$?
@@ -666,6 +515,7 @@ function main_init()
    #
    # set global project variables
    #
+   echo -n "."
    pwl_init_project
    default_define
    if [ "$?" = "1" ] ; then # no default files found, prompt & create
@@ -675,10 +525,21 @@ function main_init()
       fi
       default_define   # now load default variables
    fi
+   # 
+   # verify package files are up to date with source files
+   #
+   echo -n "."
+   $PWL_PKGMGR --update
    #
    # verify custom files are up to date with source files
    #
+   echo -n "."
    $PWL_CUSTOM --update
+   #
+   # create master index of all packages
+   #
+   echo -n "."
+   $PWL_LISTER --index -c $PKG_INDEX
    #
    $decho "end main_init"
 }
@@ -701,29 +562,15 @@ function cmd_parse_commands ()
       cmd=$1
       shift
       case "$cmd" in
-      "B"|"--boot")                # run lilo on project device
-          main_init
-          usrMode="C"
-          #
-          device_lilo
-          exit 0
-          ;;
-      "D"|"--dual-boot")           # run lilo on this drive for dual boot
-          main_init
-          usrMode="C"
-          #
-          device_dual_boot
-          exit 0
-          ;;
-      "E"|"--erase")                # erase project device
-          main_init
-          usrMode="C"
-          #
-          device_erase
-          exit 0
-          ;;
-
-      "-e"|"--extract")            # extract project files (allow copy parm)
+      "--clean")               # erase all temp package stuff non-menu command
+         $PWL_CLEAN
+         ;;
+      "--clean-factory")
+         $PWL_CLEAN --factory
+         ;;
+      "--update")              #
+         ;;
+      "--extract")            # extract project files (allow copy parm)
           main_init
           usrMode="C"
           #
@@ -736,7 +583,7 @@ function cmd_parse_commands ()
           #
           exit 0
           ;;
-      "-l"|"--load")               # copy files from project to mount point
+      "--load")               # copy files from project to mount point
           main_init
           usrMode="C"
           #
@@ -754,7 +601,7 @@ function cmd_parse_commands ()
           exit 0                   # no more parameters allowed
           ;;
 
-      "-d")                        # undocumented feature!;-)
+      "-debug")                        # undocumented feature!;-)
           if [ $debugMode = "0" ] ; then
              debug_mode  1
           else
@@ -762,18 +609,18 @@ function cmd_parse_commands ()
           fi
           ;;
 
-      "-n"|"--new")                # not a menu item, but makes sense to add here ?
+      "--new")                # not a menu item, but makes sense to add here ?
           usrMode="C"
           $PWL_PROJECTS --init $2
           exit 0
           ;;
 
-      "-h"|"--help")
+      "--help")
           usage
           exit 0
           ;;
 
-      "-v"|"--version")
+      "--version")
           echo "`basename $0` (Pee Wee Linux Configuration utility) Version $PWL_VER"
           exit 0
           ;;
diff --git a/scripts/distribute b/scripts/distribute
--- a/scripts/distribute
+++ b/scripts/distribute
@@ -1,26 +1,163 @@
-#! /bin/bash
+#!/bin/bash
 
-# scripts/distribute
+#
+# distribute
 #
 # Creates two tar archives containing binaries and sources.
 # Takes version number as commandline argument.
+#
+# Now creates 3 tar archives containing sources, basic binaries and
+# supplementary binaries
+#
+###
+#
+###
+#
 
-usage () {
+#
+# display usage information
+#
+function distribute_usage () {
     echo ""
-    echo "Usage:   distribute [version]"
-    echo "Example: distribute 0.15"
+    echo "Usage:   distribute [all|src|bin|cfg]"
+    echo ""
+    echo "           all    create all archives"
+    echo "           src    create source archive"
+    echo "           bin    create binary archive"
+    echo "           cfg    create archive of the"
+    echo "                  pwlconfig utility"
+    echo ""
+    echo "Make sure you run the clean script first"
+    echo "to get rid of build time stuff...."
     echo ""
     exit 0
 }
 
-# Test for version
-[ -z $1 ] && usage
+#
+# lsm template
+#
+lsm_template () {
+    cat <<-EOF
+	Begin3
+	Title:          PeeWeeLinux
+	Version:        ${version}
+	Entered-date:   ${todaydate}
+	Description:    A Linux distribution for embedded applications and
+	                single floppy systems. Features an ncurses graphical
+	                configuration utility. Developed on a RedHat 6.1
+	                development system.
+	Keywords:       distribution embedded floppy configuration easy X11
+	Author:         adi@adis.on.ca (Adi Linden)
+	Maintained-by:  adi@adis.on.ca (Adi Linden)
+	Primary-site:   ftp://adis.on.ca /pub/Projects/Embedded
+	                ${srcsize} ${srcname}
+	                ${binsize} ${binname}
+	                ${cfgsize} ${cfgname}
+	                1 kB  peeweelinux.lsm
+	Alternate-site: ftp://metalab.unc.edu pub/linux/distributions/peewee
+	Original-site:
+	Platforms:      
+	Copying-policy: GPL
+	End
 
-cd ../../
-tar czpf embedded-${1}-src.tar.gz Embedded_Build
+EOF
+}
 
-tar czpf embedded-${1}-bin.tar.gz Embedded_Build \
-    --exclude build_pwl \
-    --exclude sources 
+#
+# get files
+#
+
+
+#
+# create source archive
+#
+do_src () {
+    tar czpf $srcname Embedded_Build
+}
+
+#
+# create binary archive
+#
+do_bin () {
+    tar czpf $binname \
+        --exclude="Embedded_Build/src/SRPMS"   \
+        Embedded_Build
+}
+
+#
+# create pwlconfig archive
+#
+do_pwlconfig () {
+    tar czpf $cfgname \
+        Embedded_Build/scripts                 \
+        Embedded_Build/bin                     \
+        Embedded_Build/examples                \
+        Embedded_Build/pwlconfig  
+}
+
+#
+# let's do it
+#
+# test for the current working directory
+#
+if echo `pwd` | grep -q Embedded_Build$; then
+
+    # source helpful functions
+    . ./scripts/pwl_functions
+
+    # we must have a version or something went wrong!
+    if [ -z "$PWL_VER" ]; then
+        echo "A serious error occured!"
+        echo "We don't have a version!"
+        exit 1
+    fi
+
+    # define current version
+    version="$PWL_VER"
+ 
+    # define archive names
+    srcname=peeweelinux-${version}-src.tar.gz
+    binname=peeweelinux-${version}-bin.tar.gz
+    cfgname=peeweelinux-${version}-cfg.tar.gz
+
+    # change working directory
+    cd ../
+
+    # see what we should be doing
+    case $1 in
+    all)
+        do_pwlconfig
+        do_bin
+        do_src
+        #
+        # get sizes for lsm template         
+        srcsize=`du -h $srcname | cut -f 1`
+        binsize=`du -h $binname | cut -f 1`
+        cfgsize=`du -h $cfgname | cut -f 1`
+        todaydate=`date +%Y-%m-%d`
+        #
+        # output lsm template
+        lsm_template > peeweelinux.lsm
+        ;;
+    bin)
+        do_bin
+        ;;
+    src)
+        do_src
+        ;;
+    cfg)
+        do_pwlconfig
+        ;;
+    *)
+        distribute_usage
+        ;;
+    esac
+else
+
+    # Wrong root
+    echo 'This scripts needs to be run from'
+    echo '     Embedded_Build'    
+    distribute_usage
+fi
 
 exit 0
diff --git a/scripts/pwl_functions b/scripts/pwl_functions
--- a/scripts/pwl_functions
+++ b/scripts/pwl_functions
@@ -1,23 +1,10 @@
 #
-# Make sure we're really running bash.
-#
-#  History
-#   v0.90 - changed user check to allow existing .result file
-#   V0.85 - changed dir_tree_list to remove leading "/"
-#   V0.84 - check file timestamps to verify save operation is required
-#   V0.83 - updated help for context, in-file and global help support
-#   V0.3 Added all new script names, confirm_save added for all to use
-#   V0.2 Added context sensitive help option, change lxdialog message
-#   V0.1 Created from other scripts
+#  History see CHANGES.pwlconfig
 #
 [ -z "$BASH" ] && { echo "`basename $0` requires bash" 1>&2; exit 1; }
 #
 MOVE_TO_COL="echo -en \t\t"
 WHOAMI=whoami
-#
-# Release Version number
-#
-PWL_REL_VER="0.90"
 #
 # include from "scripts directory or "Embedded_Build directory
 #
@@ -31,13 +18,23 @@ else
    basedir="."    # we must be in the scripts executed as . ?
    baseprj=".."
 fi
-
+#
+# Version is set in CHANGES.pwlconfig
+#
+. ./$basedir/CHANGES.pwlconfig
+#
+PWL_REL_VER=$PWL_VER      # for backward compatability
+#
 #echo functions base: $basedir projects at: $baseprj
 #
 # utility programs, and directories may vary with distro or preference
 #
 export DIALOG="$baseprj/bin/lxdialog"
-PLILO="$baseprj/bin/lilo"
+#PLILO="$baseprj/bin/lilo"
+PLILO="lilo"
+if [ -z "$RPM" ] ; then
+   RPM=${PWD}/bin/rpm   # make sure we use v3.0.3 for now
+fi
 #
 DEV_MGR="$basedir/mkBootDevice"
 PWL_BACKUP="$basedir/pwl_backup"
@@ -48,17 +45,28 @@ PWL_FUNCTIONS="$basedir/pwl_functions"
 PWL_LISTER="$basedir/pwl_lister"
 PWL_PROJECTS="$basedir/pwl_projects"
 PWL_PKGCONF="$basedir/pwl_pkgconf"
+PWL_PKGMGR="$basedir/pwl_pkgmgr"
 PWL_UPDATE="$basedir/pwl_update"
+PWL_CLEAN="$basedir/pwl_clean"
+PWL_TARGET="$basedir/pwl_target"
+PWL_TARGETF="$basedir/pwl_target_functions"
+PWL_TARGETL="$basedir/pwl_target_load"
+PWL_ENVSEL="$basedir/pwl_envsel"
+PWL_CREATE="$basedir/pwl_create"
 RM="rm -f"
 TAR=tar
 #
 # PWL - Directories (based from installed directory)
 #
-export PRJ_DIR="$baseprj/projects"
-export PKG_DIR="$baseprj/packages"
-export SRC_DIR="$baseprj/sources"
-export SCR_DIR="$baseprj/scripts"
 export BKS_DIR="$baseprj/backups"
+export EXA_DIR="$baseprj/examples"
+export BIN_DIR="$baseprj/bin"
+export MNT_DIR="$baseprj/mnt"
+export PKG_DIR="$baseprj/packages"
+export PRJ_DIR="$baseprj/projects"
+export SCR_DIR="$baseprj/scripts"
+export SRC_DIR="$baseprj/src"
+export TMP_DIR="$baseprj/tmp"
 #
 #  project specific directories
 #
@@ -73,7 +81,7 @@ CUSTOM_LST=custom.list
 CUSTOM_SRC=custom.src
 DEFAULT_CFG=project.defaults
 CFG_Default=project.conf
-#
+PKG_INDEX=.index.list
 #
 # verify utility programs exists
 #
@@ -266,7 +274,7 @@ function debug_trace
 }
 
 #
-# debug_mode(new mode) - enable or disable debugging output features
+# debug _mode(new mode) - enable or disable debugging output features
 #
 function debug_mode()
 {
@@ -288,25 +296,37 @@ function debug_mode()
       RM=":"                # don't delete temporary files when debugging
    fi
 }
-
+####################################################################
 #
-
+#  List handlers (using lxdialog)
 #
-# show_files ( title,  pack.lst ) - show checklist of files within a package
+####################################################################
 #
-function show_files()
+# show_list ( title, list.file, prompt )
+#
+function show_list()
 {
-   if [ -z "$filesDefault" ] ; then
-      filesDefault=Add
+   $decho "start show_list: $*"
+   if [ -z "$ListDefault" ] ; then
+      ListDefault="Add"   # todo: should be head item in list.file
    fi
-   echo -n $DIALOG --title "$1" \
-                   --backtitle \"$backtitle\"       \
-                   --menu                           \
-"'Select files to include                           Project: $CFG_BASE'" \
-              $ROWS $COLS $((ROWS-8)) \
-              "'$filesDefault'" > .dialog
+   local listTitle="$1"
+   local listFile="$2"
+   local cmdPrompt="$3"
+   #
+   if [ "$cmdPrompt" = "" ] ; then
+      cmdPrompt="internal error: show_list called from $0"
+   fi
+   #$decho -e "show list for: $listTitle \n  from: $listFile\n prompt: $cmdPrompt"
+   #
+   echo -n $DIALOG --title     \""${listTitle}"\"     \
+                   --backtitle \"${backtitle}\"       \
+                   --menu      \""${cmdPrompt}"\"     \
+              $ROWS $COLS $((ROWS-8))                 \
+              "'$ListDefault'" > .dialog
 
-   cat $2 >> .dialog
+   cat $listFile >> .dialog
+
    . ./.dialog
 }
 
@@ -360,6 +380,137 @@ function show_message ()
 
    # --msgbox is undocumented feature of lxdialog (see the source vs help)
    # but wraps text lines nicely
+}
+
+
+#
+# show_files ( title,  pack.lst ) - show checklist of files within a package
+#
+function show_files()
+{
+   $decho "show_files: $*"
+    ListDefault="$filesDefault"
+    #
+    show_list "${1}" $2 \
+"Select files to include                           Project: $CFG_BASE" 
+}
+
+#
+# Displays a dialog of a list of files
+#
+function show_FileSelect()
+{
+   if [ -z "$fileSelectDefault" ] ; then
+      fileSelectDefault="\."
+   fi
+   echo -n $loc/$DIALOG --title \'$1\' \
+                   --backtitle \"$backtitle\"       \
+                   --menu                           \
+"'Select a file or traverse a directory         Project: $CFG_BASE'" \
+              $ROWS $COLS $((ROWS-8)) \
+              "'$fileSelectDefault'" > $loc/.dialog
+
+   cat $2 >> $loc/.dialog
+   . $loc/.dialog
+}
+
+#
+# FileSelect( srcPath, *resultFilename, [ ext [ Dir-Only ] ] )
+#  dialog box to display a file tree and allow it to be traversed. 
+#  returns a file that is selected or a directory as selected
+#
+function FileSelect( )
+{
+   $decho "start fileselect $*"
+   #
+   local srcpath=$1
+   local ext=$3
+   local dirOnly=$4
+   local userFile=""
+   local loc=""
+   #
+   # build list of files and display (use -p to indicate type of file)
+   #
+   loc=$PWD
+   if [ ! -d $srcpath ] ; then
+      srcpath=".."
+   fi
+   cd $srcpath
+   srcpath=$PWD
+   cd $loc
+   userFile=$srcpath    # default is directory path 
+   #
+   fileselectDone=0
+   #
+   while [ "$fileselectDone" = "0" ]; do
+      #
+      # build list of files
+      #
+      cd $srcpath
+
+      echo "../" > $loc/.fileselect.lst  # make default for empty directories
+      #
+      # always list all directories (add "/" suffix to indicate directory)
+      #
+      find -maxdepth 1 -type d | sort | gawk '{printf("%s/\n", $1 )}' >> $loc/.fileselect.lst 
+      #
+      # list type of files given or all files 
+      #
+      if [ ! -z "$ext" ] ; then
+         find -maxdepth 1 -name "$ext" | sort >> $loc/.fileselect.lst
+      else
+         find -maxdepth 1 -type f | sort >> $loc/.fileselect.lst 
+      fi
+      cd $loc
+      #
+      # clean up the files listed - remove leading ./ and blank lines
+      #   format output for lxdialog
+      #
+      sed 's/^.\///g' $loc/.fileselect.lst | sed '/^$/d' | gawk '{ \
+                 printf(" '\''%s'\'' '\''%s'\''", $1, $1 ) \
+            }' > $loc/.tmp.lst
+
+      show_FileSelect "$srcpath" .tmp.lst 2> .result
+
+      retVal=$?
+      read selection < .result
+
+      case "$retVal" in
+         1|255)                      # exit
+           fileselectDone=1
+           if [ "$dirOnly" = "" ] ; then  # if not requesting directories, 
+              userFile=""               #  then exit with blank filename
+           fi
+           ;;
+         0|3|4|5|6)                  # file or directory selected
+           if [ -f $srcpath/$selection ] ; then
+               $decho "found file $selection"
+              userFile="$srcpath/$selection"
+              fileselectDone=1
+
+           elif [ -d $srcpath/$selection ] ; then        # recurse into directory
+              $decho "traverse into directory $srcpath / $selection" 
+              cd $srcpath/$selection   # rebuild path for ".." selections
+              srcpath=$PWD
+              cd $loc
+              userFile=$srcpath
+
+           else
+              $decho "not found $srcpath  / $selection"
+              xx=1
+           fi
+         ;;
+      esac
+   done
+   # file selected, return the filename
+   #
+   $decho "file selected: $userFile"
+   eval $2=\"$userFile\"
+   #
+   cd $loc
+   $RM -rf .fileselect.lst
+   #
+   return 0     
 }
 
 #
@@ -457,26 +608,160 @@ function show_confirm ()
 
 
 #
-# dir_tree_list_all( dir_root, [ resultsFile ] )
+#  build_changed_list( changedFiles, selectedFiles, dialogLst, [addPrompt])
+#     builds a dialog of files listed in changedFiles. If the file is
+#     also found in the selectedFiles list, then it is enabled.
+#     The results of this are stored in the named dialogLst file.
+#
+function build_changed_list()
+{
+   $decho "start build_changed_list"
+   #
+   local changedList=$1
+   local selectedList=$2
+   local dialogLst=$3
+   if [ "$4" = "" ] ; then
+      addPrompt="Add Selected Files to $CFG_BASE Configuration"
+   else
+      addPrompt="$4"
+   fi
+   #
+   #  Include options to add or remove all files from this package
+   #
+   echo -n > $dialogLst
+   echo -n " 'Add'      '${addPrompt}' "         >> $dialogLst
+   echo -n " 'Skip'     '----' "                 >> $dialogLst
+   echo -n " 'Include'  'Include all files' "    >> $dialogLst
+   echo -n " 'Exclude'  'Exclude all files' "    >> $dialogLst
+   #
+   fileCnt=0
+   for fn in `cat $changedList`; do
+      #
+      if grep -q "$fn" $selectedList ; then
+         echo -n " '$fn' '[*] $fn' " >> $dialogLst
+      else
+         echo -n " '$fn' '[ ] $fn' " >> $dialogLst
+      fi
+   done
+   #
+   $decho "done build_changed_list"
+}
+
+#
+# choose_files( changedFiles, selectedFiles, title, [ execPrompt ] )
+#     Returns: 0 when user is done
+#     Returns: 1 on 'ESC' or exit
+#              selectedFiles contains list of files selected by user
+#
+function choose_files()
+{
+   $decho "begin choose_files"
+   #
+   local changedFiles=$1       # not written to
+   local selectedFiles=$2      # updated as per user selections
+   local title="$3"
+   local execPrompt="$4"
+   #
+   local filesDone=0
+   local selection=""
+   local retVal=""
+   local retStatus=""
+   #
+   filesDefault="Add"          # default to top of list
+   #
+   # if none are selected, default to all selected
+   #
+   if [ ! -s $selectedFiles ] ; then
+      $decho "defaulting to all selected"
+      cp -f $changedFiles $selectedFiles
+   fi
+   #
+   while [ "$filesDone" = "0" ] ; do
+      #
+      build_changed_list $changedFiles $selectedFiles .select.lst "$execPrompt"
+      #
+      show_files "$title" .select.lst 2> .result
+      retVal=$?
+      read selection < .result
+      filesDefault=$selection   # set global default variable
+      #
+      case "$retVal" in
+         1|255)                      # exit
+            retStatus=1
+            filesDone=1
+           ;;
+         2)                          # help
+            sed -n /^######/,/^######/p $0 | sed 's/^#*//g' > pwl_update.README
+            show_help pwl_update.README
+           ;;
+         0|3|4|5|6)                  # toggle project or operate on current
+           #
+           case "$selection" in
+             "Add")
+                retStatus=0
+                filesDone=1
+                ;;
+             "Include")                  # operation "Include"
+                cp -f $changedFiles $selectedFiles
+                ;;
+             "Exclude")
+                echo -n "" > $selectedFiles
+                ;;
+             "Total"|"Skip"|"skip")
+                xx=1 # do nothing
+                ;;
+             *)                      # list item selected
+                if grep -q $selection $selectedFiles; then
+                   grep -v $selection $selectedFiles > .tmp
+                   cp -f .tmp $selectedFiles
+                else
+                   echo $selection >> $selectedFiles
+                fi
+                ;;
+           esac       # end select item
+           ;;
+       esac    # end dialog response
+
+   done    # end while configuring
+   #
+   $RM -f .tmp .result
+   $decho "done choose_files"
+   return $retStatus
+}
+
+#############################################################################
+#
+# dir_tree_list_all( dir_root [, resultsFile [, find_option  ] )
 #         - builds a list of all files found in the given dir_root
 #
 function dir_tree_list_all()
 {
-   loc=$PWD
-   cd $1
+   local lstDir=$1
+   local resFn=".result"
+   local findOpt=""
    #
-   # list files, remove file size and leading dot, remove blank lines
-   #     remove leading / also
+   if [ "$2" != "" ] ; then          # optional second arg
+      resFn="$2"
+      if [ "$3" != "" ] ; then       #  optional third arg
+         findOpt="$3"
+      fi
+   fi
    #
-   du . -a | cut -f2 | cut -d. -f2- | sed /^$/d | sort -u | sed "s/^\/*//g" > $loc/.result
+   local loc=$PWD
+   cd $lstDir
+   #
+   # list directories and files within the current directory
+   #
+   find ${findOpt}   > $loc/.tmp_tree
+   # find ${findOpt} -type d  >> $loc/.tmp_tree
    #
    cd $loc
    #
-   # update to given file if specified
+   # sort and remove leading ./ characters
    #
-   if [ ! -z "$2" ] ; then
-      cp $loc/.result $2
-   fi
+   sort -u .tmp_tree | sed -e "s/^\.//g" -e "s/^\///g" > $resFn
+   #
+   $decho "built list of files in $resFn from $lstDir using $findOpt"
 }
 
 
@@ -584,7 +869,7 @@ function usage()
 }
 
 #
-# default_define - parse defaults file and set variables
+# default_define - parse defaults file, set variables, check version
 #
 function default_define()
 {
@@ -600,6 +885,17 @@ function default_define()
    else
       $decho "default not found"
       status=1
+   fi
+   #
+   # set our deviceName depending on our configuration
+   # and only if rd_floppy or rd_target are defined
+   #
+   if [ -n "$rd_floppy" -o -n "$rd_target" ]; then
+       if echo "$target_scheme" | grep -q "^fd"; then
+           export deviceName="$rd_floppy"
+       else
+           export deviceName="$rd_target"
+       fi
    fi
    #
    $decho "end default_define"
diff --git a/scripts/pwl_pkgconf b/scripts/pwl_pkgconf
--- a/scripts/pwl_pkgconf
+++ b/scripts/pwl_pkgconf
@@ -18,10 +18,6 @@
 #
 ###
 #
-# History:
-#   v0.85 - replaced paths to temp file with CFG_FILE_TMP
-#   v0.1 - created
-#
 # Comments:
 #
 ######
@@ -88,7 +84,7 @@ else
   echo "script pwl_functions not found"
 fi
 #
-PWL_PKGCONF_VER=${PWL_REL_VER}".1"
+PWL_PKGCONF_VER=${PWL_REL_VER}".2"
 #
 #
 #=============================================================================
@@ -133,12 +129,14 @@ function build_pwl_pkgconf ()
    #  allow custom files operation
    #
    echo -n " 'Unique' 'Configure Custom files for \"$CFG_BASE\" -->' " > $1
+   echo -n " 'Search' 'Search available Packages -->' " >> $1
+   echo -n " 'Depend' 'Check configuration dependencies -->' " >> $1
    echo -n " 'Skip'   '----' " >> $1
    #
    # list all subdirectories files found in packages directory
    #
    gotOne=0
-   for pkgDirName in `find $2 -type d | sort`;
+   for pkgDirName in `find $2 -type d -maxdepth 1 | sort`;
    do
       #
       # show directory names (except root of this directory)
@@ -255,12 +253,13 @@ function build_pkg_list()
    #
    totalSz=0
    for sysFn in `cat $pkgDir/$pkgFn".list"`; do
-      echo -n "."   # show user we are doing something
+      echo -n "."      # show user we are doing something
       #
       # read filesize for this file (file size must be at start of line)
       #
-      if grep -q $sysFn$ .result ; then
-         fileSz=`grep $sysFn$ .result | cut -d" " -f1`
+      if grep -q "$sysFn$" .result ; then
+         # not sure how, might get two lines here-in...
+         fileSz=`grep "$sysFn$" .result | cut -d" " -f1 | head -1`
       else
          fileSz=0
       fi
@@ -268,8 +267,8 @@ function build_pkg_list()
       # if file is in the status list file then flag it
       #    use Exact match, allow empty directory select
       #
-      if grep -q $sysFn$ "$PWL_PRJ"/.$pkgFn".list" ; then
-        echo -n "'$sysFn' '[*] $sysFn "  >> $2
+      if grep -q "$sysFn$" "$PWL_PRJ"/.$pkgFn".list" ; then
+        echo -n " '$sysFn' '[*] $sysFn "  >> $2
         totalSz=`expr $totalSz + $fileSz`
       else
          echo -n "'$sysFn' '[ ] $sysFn " >> $2
@@ -293,11 +292,13 @@ function build_pkg_list()
 #
 function project_package_default()
 {
-   $decho "start project_package_default"
-     #
-     #  list files found in the package directory
-     #
-     for lstFile in `ls $2/*list 2> /dev/null` ; do
+   $decho "start project_package_default $*"
+   #
+   local defaultDir=$2
+   #
+   #  list files found in the package directory
+   #
+   for lstFile in `ls $defaultDir/*list 2> /dev/null` ; do
         #
         # copy or remove list files from current configuration
         #
@@ -305,17 +306,19 @@ function project_package_default()
            grep -v "$lstFile"$ $1 > .result
            cp .result $1
         else
+           $decho "Including $lstFile into $1"
            echo $lstFile >> $1
            build_files_verify "$lstFile"  #create config files as required
         fi
-     done
-     if [ -f $1 ] ; then           #   if any added or removed, sort them
-        cat $1 | sort -u > .result
-        cp .result $1
-     else
-        echo -n "" > $1
-     fi
-  $decho "done project_package_default"
+   done
+   #
+   if [ -f $1 ] ; then           #   if any added or removed, sort them
+      cat $1 | sort -u > .result
+      cp .result $1
+   else
+      echo -n "" > $1
+   fi
+   $decho "done project_package_default"
 }
 
 #
@@ -373,11 +376,300 @@ function pwl_pkgconf_save()
    return 0
 }
 
+#
+# pwlconf_do_search( expression, matching files, selected matching files )
+#    Finds all files in the packages that matches the given expression. 
+#    from this list, builds a list of files that are currently selected
+#    the results are posted in the "selected_matching_files" file
+#
+function pkgconf_do_search()
+{
+   $decho "start pkgconf_do_search"
+   #
+   local expression="$1"
+   local searchList=$2
+   local searchEnabled=$3
+   #
+   # make sure we have our database file
+   #
+   if [ ! -s $PKG_INDEX ] ; then
+      $PWL_LISTER --index -c $PKG_INDEX
+   fi
+   #
+   # show package files and custom files that match
+   #  - list all available package files that match
+   #  - build list in format "path/packages:file" from global index file
+   #
+   echo -n > $searchList
+   pkgpath=`basename $PKG_DIR`
+   cut -f2 -d":" $PKG_INDEX | grep "${expression}" > .search.files    
+   for selFn in `cat .search.files` ; do
+     grep $selFn $PKG_INDEX | sed "s!${pkgpath}\/!!g" >> $searchList
+     echo -n "."
+   done
+   #
+   # show as selected all files that match from current configuration
+   #    (NOT including our temporary configuration)
+   #
+   grep "${expression}" $PWL_PRJ/*.list | sed "s!$PWL_PRJ!!g"  > .search.selected
+   #
+   # note we could select some files here which are not in 
+   #  project configuration (you can configure a package, then not include
+   #  the package) Thus, we must verify against the configuration file
+   #
+   echo -n "" > .search.conf
+   for selFn in `cat $PWL_PRJ/$CFG_Default` ; do
+       # find just the filename in the project configured packages
+       # 
+       grep `basename $selFn` .search.selected >> .search.conf
+       echo -n "."
+   done
+   #
+   # Now we know  "package:files" that are included in the project. Show
+   # them as enabled by choosing them from the list of all matching files.
+   #
+   echo -n "" > $searchEnabled
+   for selFn in `cat .search.conf` ; do
+      grep $selFn $searchList >> $searchEnabled
+      echo -n "."
+   done
+   #
+   # Also show the matching custom files - custom files are always selected
+   #
+   if [ -f "$PWL_PRJ/.$CUSTOM.LST" ] ; then
+      grep "${expression}" $PWL_PRJ/.$CUSTOM.LST   >> $searchList
+      grep "${expression}" $PWL_PRJ/.$CUSTOM.LST   >> $searchEnabled
+      #
+   elif [ -f "$PWL_PRJ/$CUSTOM.LST" ] ; then
+      grep "${expression}" $PWL_PRJ/$CUSTOM.LST    >> $searchList
+      grep "${expression}" $PWL_PRJ/$CUSTOM.LST    >> $searchEnabled
+   fi
+   #
+   $RM .search.files .search.conf .search.selected
+   $decho "done pkgconf_do_search"
+}
+
+#
+# pkgconf_search
+#    Performs a search by users expression and displays matching files
+#    for interactive picking and choosing.
+#
+function pkgconf_search()
+{
+   $decho "start pkgconf_search $*"
+   #
+   local exprIn=""
+   #
+   get_string "Search For Available Files"          \
+              "Enter regular Expression to search:" \
+               exprIn 
+   retVal=$?
+   if [ "$retVal" != "0" ] ; then
+      $decho "no expression entered"
+      return
+   fi
+   #
+   pkgconf_do_search  "$exprIn"  .search.lst .search.enabled
+   #
+   if [ ! -s .search.lst ]  ; then
+      show_message "No Matches found" "Failed to find any match for: $exprIn"
+   else
+      # save the current configuration
+      sort -u .search.enabled > .search.original
+      #
+      # allow user to choose which files are desired
+      #
+      choose_files .search.lst .search.enabled "Search Results"
+      retVal=$?
+      if [ $retVal = "0" ] ; then
+         #
+         $decho "accepting selected files"
+         pkgconf_add_delete add .search.enabled
+         #
+         $decho "disable  unselected items"
+         comm -23 .search.original .search.enabled > .search.disabled
+         pkgconf_add_delete delete .search.disabled
+      fi
+   fi
+   $RM .search.lst .search.enabled .search.original .search.disabled
+   $decho "done pkgconf_search"   
+}
+
+#
+#  pkgconf_add_delete ( [ add | delete ], list_pkg:file_file, [ verbose ] )
+#    Adds or deletes each file and it's package.  The list file contains
+#    package:filename format
+#
+function pkgconf_add_delete
+{
+   $decho "starting pkgconf_add_delete $*"
+   #
+   local enable=$1
+   local listPkgFiles=$2
+   #
+   for pathPkgFn in `cat $listPkgFiles` ; do
+      echo -n "."
+      pkgFn=`echo $pathPkgFn | cut -f2 -d":"`
+      pkgDirList=`echo $pathPkgFn | cut -f1 -d":"`
+      pkgListFn=`basename $pkgDirList`
+      #
+      if [ $enable = "add" ] ; then
+         #
+         [ "$3" != "" ] && echo "Adding $pathPkgFn"
+         #
+         # make sure package is part of project configuration
+           echo $PKG_DIR/$pkgDirList >> $CFG_FILE_TMP
+         #  
+         # make sure temporary configuration file exists
+           if [ ! -f $PWL_PRJ/.$pkgListFn ] ; then
+              if [ -f $PWL_PRJ/$pkgListFn ] ; then
+                 cp $PWL_PRJ/$pkgListFn $PWL_PRJ/.$pkgListFn
+              fi
+           fi
+         #
+         # add the file to the package list
+           echo $pkgFn >> $PWL_PRJ/.$pkgListFn
+         #
+      elif [ $enable = "delete" ] ; then
+         #
+         # remove file from list of enabled package files
+           if [ -f $PWL_PRJ/.$pkgListFn ] ; then
+              grep -v "$selection" "$PWL_PRJ"/.$pkgListFn > .result
+              sort -u .result > "$PWL_PRJ"/.$pkgListFn
+           fi
+         #
+      else
+         $decho "internal error: parameter add or delete only"
+      fi
+   done
+   $decho "done pkgconf_add_delete"
+}
+
+#
+# pkgconf_list_depends( dependsListFn, projectIndexFn )
+#
+#   - creates a list of dependancies assigned to the files in the project
+#   - projectIndexFn lists all files assigned in the project
+#
+function pkgconf_list_depends()
+{
+   local dependsFn=$1
+   local projectFn=$2
+   #
+if [ -s $dependsFn ] ; then
+   xx=1   # depends exists...don't make it again..for debug only
+   echo skipping build depends for debug...
+   read x
+else
+   echo -n "" > $dependsFn
+   echo -n "" > $projectFn
+   # 
+   for packageFn in `cat $CFG_FILE` ; do
+      echo "Checking dependents in package: $packageFn"
+      #
+      packageCfg=${PWL_PRJ}/`basename $packageFn`
+      echo "# Dependancies for package: $packageCfg" >> $dependsFn
+      #
+      # get all enabled files from the package list file, don't check 
+      #       on directories
+      #
+      for installedFn in `cat $packageCfg | grep -v "\/$"` ; do
+          echo -n "."
+          # maintain a list of all project files
+          #   
+          echo "/$installedFn" >> $projectFn
+          #
+          # check each file for it's dependencies
+          #
+          $PWL_PKGMGR --depends "/${installedFn}" >> $dependsFn 2> /dev/null
+      done
+      echo "."
+   done
+fi
+   #
+   $decho "done pkgconf_list_depends"
+}
+
+#
+#
+#
+function pkgconf_depends()
+{
+   $decho "start pkgconf_depends"
+   #
+   # check the project files and custom files for dependencies
+   #
+   pkgconf_list_depends        .dep.depends .prj.index.$CFG_BASE
+   $PWL_CUSTOM --depends    >> .dep.depends
+   cat $PWL_PRJ/$CUSTOM_LST >>              .prj.index.$CFG_BASE
+   #
+   # of all the depend files, list files not yet included in project
+   # - remove comments and grep from the project index
+   # - note the dependant files listed do not include their path
+   #
+   echo -n "" > .dep.needs
+   sort -u .dep.depends | grep -v "^#" > .dep.tmp
+   #
+   for depFn in `cat .dep.tmp` ; do
+      if ! grep -q "$depFn" .prj.index.$CFG_BASE ; then
+         echo $depFn >> .dep.needs
+         echo -n "."
+      fi
+   done
+   #
+   # allow user to choose dependent files to be included in project
+   #
+   if [ -s .dep.needs ] ; then
+      echo -n "" > .dep.enabled    # none are selected yet
+      echo -n "" > .dep.add        # list of packages:files to add
+      echo -n "" > .dep.notfound   # list of depends not found
+      #
+      choose_files .dep.needs .dep.enabled "Dependancy Results"
+      retVal=$?
+      if [ $retVal = "0" ] ; then
+         #
+         $decho "accepting selected files"
+         #
+         # search files in index and build list of package:file
+         #
+         for depFn in `cat .dep.enabled` ; do 
+            if grep -q "$depFn" $PKG_INDEX  ; then
+               grep "${depFn}" $PKG_INDEX >> .dep.add
+            else
+               echo $depFn >> .dep.notfound
+            fi
+         done
+         #
+         if [ -s .dep.notfound ] ; then
+            echo "The following dependent files were not found in any available " > .dep.results
+            echo "package files.  Upgrade your packages or add as custom files." >> .dep.results
+            echo "---" >> .dep.results
+            cat .dep.notfound >> .dep.results
+            show_results .dep.results "Dependent Files not located"
+         fi
+         #
+         if [ -s .dep.add ] ; then
+            pkgconf_add_delete add .dep.add VERBOSE > .dep.results
+         else
+            echo "No dependent files were found, none were added." > .dep.results
+         fi
+         #
+         show_results .dep.results "Depend files added"
+      fi
+   fi
+   #
+   $RM .dep.add .dep.enabled .dep.needs .dep.tmp .prj.tmp .dep.results
+   $RM .dep.notfound
+   $decho "done pkgconf_depends"
+}
 
 #=============================================================================
 #
-#
 # menu_pwl_pkgconf ( packageDirectory, [defaultItem] )
+#
+#   Display packages and allow user to enable/disable any package.
+#   Menu contains commands for custom configuration, search and depend
+#   checks.
 #
 function menu_pwl_pkgconf()
 {
@@ -427,6 +719,12 @@ function menu_pwl_pkgconf()
 
               "Unique")
                  $PWL_CUSTOM
+                 ;;
+              "Search")
+                 pkgconf_search
+                 ;;
+              "Depend")
+                 pkgconf_depends
                  ;;
 
               "Total"|"Skip"|"skip")
@@ -493,7 +791,7 @@ function menu_pkg_list()
       #
       build_pkg_list $1 .pack.lst
       #
-      show_files "'Configure Files Menu'" .pack.lst 2>.result
+      show_files "Configure Files Menu" .pack.lst 2>.result
       retVal=$?
       read selection <.result
       filesDefault=$selection
diff --git a/scripts/pwl_projects b/scripts/pwl_projects
--- a/scripts/pwl_projects
+++ b/scripts/pwl_projects
@@ -13,10 +13,6 @@
 #   --project project name       use this project (default is last project)
 ###
 #
-# History:
-#   v0.85 - Changed "project not saved" message
-#   v0.1 - created
-#
 # Comments:
 ######
 #pwl_projects.README
@@ -37,12 +33,11 @@
 #
 # "Create a New Project"
 #
-#    Selecting this option will prompt you for the name of your new
-#    project.
+#    Selecting this option will allow you to either create a new   
+#    project or select one of the available example projects.
 #
-#    Along with the project name, you will be prompted for the initial
-#    device: DOC, FLASH, Floppy, CDROM.  Enter one of these for
-#    setting defaults for your project.
+#    The example projects are there for you to practice or use as
+#    a base for you own development work.
 #
 # "Copy <project> to New Project"
 #
@@ -73,12 +68,6 @@
 #    This allows you to create backup files for various items within
 #    the project and the PWL envronment. See on-line help for this
 #    menu for further explanation.
-#
-# "Project defaults for <project>"
-#
-#    This allows you to set some global "project" specific parameters
-#    such as mount points, device types and so on. See on-line help
-#    for this menu for further explanation.
 #
 # [] <project name 1>
 # [] <project name 2>
@@ -146,7 +135,6 @@ function build_project ()
          echo -n " 'Remove'  'Remove Project \"$CFG_BASE\" -->' "      >> $1
          echo -n " 'Archive' 'Backup/Restore Projects and Environment -->' " >> $1
          echo -n " 'skip'   '------' " >> $1
-         echo -n " 'Default' 'Project defaults for \"$CFG_BASE\" -->' " >> $1
       fi
       #
       # list all project files found in project directory
@@ -220,6 +208,7 @@ function projects_define_last()
    #
    cat <<- EOF > $PRJ_LAST
        export CFG_BASE="$CFG_BASE"
+       export DEFAULT_CFG="$DEFAULT_CFG"
 	EOF
 #^^ tab character here!!
    $decho "end projects_define_last"
@@ -274,55 +263,6 @@ revert back to your last \"saved\" configuration select 'No'."  10
    $decho "end projects_assign"
 
    return 0
-}
-
-#
-# projects_new( [ new name ] ) - prompts user and creates new project
-#
-function projects_new()
-{
-   $decho "start projects_new $*"
-   # create a new project
-   if [ "$1" = "" ] ; then
-      #
-      # prompt for project name if not provided
-      #
-      get_string "Create New Project" \
-                 "Enter name of new Project to Create" \
-                 "newName"
-      retVal=$?
-      if [ "$retVal" != "0" ] ; then
-         $decho "end projects_new none $retVal"
-         return 1
-      fi
-   else
-      newName=$1
-   fi
-   #
-   if [ ! -z "$newName" ] ; then
-      #
-      #  set temp variable to new path/name
-      #
-      newDir="$PRJ_DIR"/"$newName"
-      #
-      # create a new configuration
-      #
-      if [ -d $newDir ] ; then
-      #
-         show_message "Error: Could not create Project" \
-                      "Project \"$newDir\" Already Exists"
-         status=1
-      else
-         #
-         #  setup new project
-         #
-         projects_assign $newName
-         status=$?
-         #
-      fi
-   fi
-   $decho "end projects_new 0"
-   return $status
 }
 
 #
@@ -431,11 +371,12 @@ function menu_projects()
                 projects_remove       # prompt to confirm and kill it
                 ;;
              "Add")
-                projects_new          # prompt for new project name and create it
-                if [ "$?" = "0" ] ; then
-                   # valid new project, assign new device defaults
-                   $PRJ_DEFAULTS --reset
+                $PWL_CREATE
+                if [  "$?" = "0" -a -s .newName ]; then
+                    projects_assign `cat .newName` 
                 fi
+                # cleanup
+                $RM .newName
                 ;;
              "Copy")
                 projects_copy         # Prompt for source and destination and duplicate
@@ -469,7 +410,7 @@ function menu_projects()
    #
    # return clean
    #
-   $RM .result .select.lst pwl_projects.README
+   $RM .result .select.lst pwl_projects.README .newName
    #
    $decho "end menu_project"
    if [ -z "$CFG_BASE" ] ; then
@@ -519,13 +460,6 @@ function projects_init()
       #
       projects_assign $CFG_BASE
       status=$?
-   #
-   elif [ ! -d $PRJ_DIR ] ; then
-      #
-      $decho "new project directory, prompt for project"
-      #
-      projects_new
-      status=$?
    else
       #
       $decho "no default listed, check for existing projects"
@@ -536,13 +470,17 @@ function projects_init()
          eval firstPrj=`head -1 .result`
          projects_assign $firstPrj
          status=$?
-      #
+         #
       else
          #
-         $decho "clean installation, create new project"
-         #
-         projects_new
+         $PWL_CREATE
          status=$?
+         if [  "$?" = "0" -a -s .newName ]; then
+             projects_assign `cat .newName`
+             status=$?
+         fi
+         # cleanup
+         $RM .newName
       fi
       #
    fi
